# Generated by Django 4.0 on 2023-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
