# Generated by Django 4.0 on 2023-03-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='start',
            new_name='start_date',
        ),
    ]
