# Generated by Django 4.0 on 2023-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(related_name='categories', to='products.Category', verbose_name='Подкатегория'),
        ),
    ]
