# Generated by Django 4.0 on 2023-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='products.Category', verbose_name='Подкатегория'),
        ),
    ]
